quarkus:
  log:
    json:
      log-format: ecs
      fields:
        mdc:
          flat-fields: true
        timestamp:
          field-name: '@timestamp'
        level:
          field-name: log.level
        logger-name:
          field-name: log.logger
  kotlin-serialization:
    json:
      ignore-unknown-keys: true
lambda:
  mailgun:
    signing-key: "ffffffff"
  aws:
    account-id: "000000000000"

"%test":
  quarkus:
    log:
      console:
        enable: false
  lambda:
    aws:
      region: "eu-west-1"